---
title: "Naive bayes model-Sample dataset"
author: "viplove"
date: "10 November 2017"
output: html_document
---

```{r}
# 1) Attached is a 'sample data' and below are the features of the data. Review the sample data
# (Model_Data_sample.csv) and the description below. Build an understanding of the data and plan
# your approach to build a model
nb_sample=read.csv("file:///D:/ML Datasets/Model_Data_Sample.csv")


# 2) Define your data exploration, imputation and visualization approach
# No imputation used,result derived by using the original dataset.

# Naive Bayes
#Only age will be remaining 
# names(nb_sample)=paste("age")
# for changing column name
# nb_sample=rename(nb_sample,"age1"="age")


# 4) Set seed for sampling (your roll number)
set.seed(53)


# 5) Split model into train(80%) and test data(20%)
install.packages(e1071)
library(e1071)
nb_sample=read.csv("file:///D:/ML Datasets/Assignment - 3 update/Model_Data.csv")
names(nb_sample)=c("age","workclass","fnlwgt","education","educationnum","maritalstatus","occupation","relationship","race","sex","capitalgain","capitalloss","hpw","nativecountry","compensation")
sample=sample.int(n=nrow(nb_sample),size=floor(.8*nrow(nb_sample)),replace=F)
nb_sample_train=nb_sample[sample,]
nb_sample_test=nb_sample[-sample,]


# 6) Build 3 Models, each using one of different type of algorithm. Send me the model building command. (1 mark each + 1 for creative "DS" think = total 4 marks)

#  model1 = Naive bayes classifier
model=naiveBayes(compensation~.,data=nb_sample_train[,-14])
pred=predict(model,nb_sample_test[,-15])
confmat=table(pred,nb_sample_test$compensation)
accuracy=sum(diag(confmat))/sum(confmat)

# model2 = KNN
knn_train_data=knn_sample[sample1,c(1,3,5,11,13,12)]
knn_test_data=knn_sample[-sample1,c(1,3,5,11,13,12)]
knn_train_label=knn_sample[sample1,14]
knn_test_label=knn_sample[-sample1,14]
install.packages("class")
library(class)

k=5
pc_pred_label=knn(train = knn_train_data,
                  test=knn_test_data,
                  cl=knn_train_label,
                  k)
confmat=table(knn_test_label,pc_pred_label)
accuracy=sum(diag(confmat))/sum(confmat)

#  model3 = Decision Tree
tree.model.dt=tree(compensation~.,data=dt_sample_train[, -14])
modelprediction=predict(tree.model.dt,dt_sample_test[, -14])
maxidx=function(arr){
  return(which(arr==max(arr)))
}
idx=apply(modelprediction,c(1),maxidx)
model_prediction=c('<=50K','>50K')[idx]
confmat=table(model_prediction,dt_sample_test$compensation)
accuracy=sum(diag(confmat))/sum(confmat)


# 7) Predict your model performance on each of the 3 models and submit
# model_accuracy=55.01
# model_accuracy2=89.12
# model_accuracy3=56.15

# 8) Generalization
# If we compare all the 3 models, we can infer that the KNN model is providing the best accuracy for our dataset, hence we can go with this model for out dataset and even if we change the value of k the accuracy will remain between the range of 80 and 90.

# 9) Upload details into your account on GIT Hub


```

```{r}
# knn
knn_sample=read.csv("file:///D:/ML Datasets/Assignment - 3 update/Model_Data.csv")
names(knn_sample)=c("age","workclass","fnlwgt","education","educationnum","maritalstatus","occupation","relationship","race","sex","capitalgain","capitalloss","hpw","nativecountry","compensation")

knn_train_data=knn_sample[sample1,c(1,3,5,11,13,12)]
knn_test_data=knn_sample[-sample1,c(1,3,5,11,13,12)]
knn_train_label=knn_sample[sample1,14]
knn_test_label=knn_sample[-sample1,14]

#install.packages("class")
library(class)

k=5

pc_pred_label=knn(train = knn_train_data,
                  test=knn_test_data,
                  cl=knn_train_label,
                  k)

confmat=table(knn_test_label,pc_pred_label)

accuracy=sum(diag(confmat))/sum(confmat)
```

```{r}

# Decision tree
dt_sample=read.csv("file:///D:/ML Datasets/Assignment - 3 update/Model_Data.csv")
names(dt_sample)=c("age","workclass","fnlwgt","education","educationnum","maritalstatus","occupation","relationship","race","sex","capitalgain","capitalloss","hpw","nativecountry","compensation")


install.packages("tree")
require(tree)
sample2=sample.int(n=nrow(dt_sample),size=floor(.8*nrow(dt_sample)),replace=F)
dt_sample_train=dt_sample[sample2,]
dt_sample_test=dt_sample[-sample2,]

# dt_sample$workclass=gsub("\\")
# mice_mod=mice(dt_sample,c("workclass","occupation","nativecountry"),method='rf')
set.seed(53)
tree.model.dt=tree(compensation~.,data=dt_sample_train[, -14])

modelprediction=predict(tree.model.dt,dt_sample_test[, -14])
maxidx=function(arr){
  return(which(arr==max(arr)))
}

idx=apply(modelprediction,c(1),maxidx)
model_prediction=c('<=50K','>50K')[idx]
confmat=table(model_prediction,dt_sample_test$compensation)
accuracy=sum(diag(confmat))/sum(confmat)

```